### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by anton-kazlouski** [MtzwOsk/shipment-app#1]
Hello! Thanks for your time and efforts. Below you can find some thoughts regarding the homework.

BE:
1. shipments.models.ShipmentModel -- Just Shipment would be fine
2. I guess TODO comments in models.py left as an intention to show how you would improve it
3. Views could be simplified by using mixins
4. TODO comments are unclear in views.py, thus it is not clear why they are in place
5. Comments in tests seem to be redundant.
6. self.assertEqual(ShipmentModel.objects.filter(title=title).exists(), True) --> self.assertTrue()

FE:
The structure is ok, the code is not overcomplicated. However, there is no any interaction with a user. At least I would expect some kind of notification that a shipment has been created or not. Also, it would be nice to see a bit more pretty design.

In order to proceed to our end customer, I would recommend to polish the project: remove TODO comments, remove redundant comments, remove logging to console etc.

Please, don't hesitate to ask any questions.

**Comment by MtzwOsk** [comment]
@anton-kazlouski  
Thank you for review.
Ofcourse I will improve project.

**Comment by MtzwOsk** [comment]
Concerning Your comments, I made some changes. There was indeed a lot of TODOs, I wanted to show some ways because we didn't mention specific rules about the task.

I hope now looks better.
