### ISSUE TITLE
Feedback #2

### ISSUE THREAD

**Issue by anton-kazlouski** [MtzwOsk/shipment-app#2]
Hello! Sorry for the delay. Thanks for the update. Bellow you can find some observation regarding the code:
1. Views can be simplified even more. It should be possible to use only one serializer for a view class.
2. Here and there I can see redundant comments like
```
    def test_create_shipment(self):
        """
        Create Shipment
        """
```
3. I failed to make npm run serve work. Tried different node version but it won't run:
<img width="1195" alt="Screenshot 2022-08-10 at 16 54 58" src="https://user-images.githubusercontent.com/55976782/183941455-14f642d5-7447-4c73-a13f-9fe655f7b99f.png">

**Comment by MtzwOsk** [comment]
Thanks you for CR.

1. Done
2. Done
3. Done. Vuetify is in newest beta version does not add version inside to package.json...
