### ISSUE TITLE
Feedback #3

### ISSUE THREAD

**Issue by anton-kazlouski** [MtzwOsk/shipment-app#3]
Hello! Thanks for the quick update.
I've had an issue with yarn:
 ERROR  Error: The project seems to require yarn but it's not installed.
Once installed dev server was able to start.
 
One more thing:
There is no need to run npm run serve before creating a built. Probably it just a typo.

I think at this point we will proceed to our customer. They can be pretty slow with response, but we will try to push them.

**Comment by MtzwOsk** [comment]
Hi 
Thank you.
I made changes in README
- add yarn version info, 
- remove "npm run serve"
